from .nodes import (
    Qwen3Loader,
    Qwen3CustomVoice,
    Qwen3VoiceDesign,
    Qwen3VoiceClone,
    Qwen3BaseCustomVoiceCloneInstruct,
    Qwen3DirectedCloneFromVoiceDesign,
    Qwen3PromptMaker,
    Qwen3ClonePromptFromAudio,
    Qwen3SavePrompt,
    Qwen3LoadPrompt,
    Qwen3CustomVoiceFromPrompt,
    Qwen3HybridCloneInstructPreset,
    Qwen3VoiceBoxInstruct,
    Qwen3VoiceBoxClone,
    Qwen3VoiceBoxCloneInstruct,
    Qwen3VoiceBoxCloneExperiment,
    Qwen3VoiceBoxMorphSpeaker,
    Qwen3DatasetFromFolder,
    Qwen3DataPrep,
    Qwen3FineTune,
    Qwen3PlainCustomVoiceFineTune,
    Qwen3VoiceBoxCreate,
    Qwen3UploadVoiceBoxToHub,
    Qwen3VoiceBoxBootstrapFineTune,
    Qwen3VoiceBoxFineTune,
    Qwen3SFTBase12Hz,
    Qwen3SFTCustomVoice12Hz,
    Qwen3SFTVoiceBox12Hz,
    Qwen3SFTVoiceBoxBootstrap12Hz,
    Qwen3AudioCompare
)

NODE_CLASS_MAPPINGS = {
    "Qwen3Loader": Qwen3Loader,
    "Qwen3CustomVoice": Qwen3CustomVoice,
    "Qwen3VoiceDesign": Qwen3VoiceDesign,
    "Qwen3VoiceClone": Qwen3VoiceClone,
    "Qwen3BaseCustomVoiceCloneInstruct": Qwen3BaseCustomVoiceCloneInstruct,
    "Qwen3DirectedCloneFromVoiceDesign": Qwen3DirectedCloneFromVoiceDesign,
    "Qwen3PromptMaker": Qwen3PromptMaker,
    "Qwen3ClonePromptFromAudio": Qwen3ClonePromptFromAudio,
    "Qwen3SavePrompt": Qwen3SavePrompt,
    "Qwen3LoadPrompt": Qwen3LoadPrompt,
    "Qwen3CustomVoiceFromPrompt": Qwen3CustomVoiceFromPrompt,
    "Qwen3HybridCloneInstructPreset": Qwen3HybridCloneInstructPreset,
    "Qwen3VoiceBoxInstruct": Qwen3VoiceBoxInstruct,
    "Qwen3VoiceBoxClone": Qwen3VoiceBoxClone,
    "Qwen3VoiceBoxCloneInstruct": Qwen3VoiceBoxCloneInstruct,
    "Qwen3VoiceBoxCloneExperiment": Qwen3VoiceBoxCloneExperiment,
    "Qwen3VoiceBoxMorphSpeaker": Qwen3VoiceBoxMorphSpeaker,
    "Qwen3DatasetFromFolder": Qwen3DatasetFromFolder,
    "Qwen3DataPrep": Qwen3DataPrep,
    "Qwen3FineTune": Qwen3FineTune,
    "Qwen3PlainCustomVoiceFineTune": Qwen3PlainCustomVoiceFineTune,
    "Qwen3VoiceBoxCreate": Qwen3VoiceBoxCreate,
    "Qwen3UploadVoiceBoxToHub": Qwen3UploadVoiceBoxToHub,
    "Qwen3VoiceBoxBootstrapFineTune": Qwen3VoiceBoxBootstrapFineTune,
    "Qwen3VoiceBoxFineTune": Qwen3VoiceBoxFineTune,
    "Qwen3SFTBase12Hz": Qwen3SFTBase12Hz,
    "Qwen3SFTCustomVoice12Hz": Qwen3SFTCustomVoice12Hz,
    "Qwen3SFTVoiceBox12Hz": Qwen3SFTVoiceBox12Hz,
    "Qwen3SFTVoiceBoxBootstrap12Hz": Qwen3SFTVoiceBoxBootstrap12Hz,
    "Qwen3AudioCompare": Qwen3AudioCompare
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "Qwen3Loader": "Qwen3-TTS Loader",
    "Qwen3CustomVoice": "Qwen3-TTS Custom Voice",
    "Qwen3VoiceDesign": "Qwen3-TTS Voice Design",
    "Qwen3VoiceClone": "Qwen3-TTS Voice Clone",
    "Qwen3BaseCustomVoiceCloneInstruct": "Qwen3-TTS Base+CustomVoice Clone+Instruct",
    "Qwen3DirectedCloneFromVoiceDesign": "Qwen3-TTS Directed Clone From Voice Design",
    "Qwen3PromptMaker": "Qwen3-TTS Prompt Maker",
    "Qwen3ClonePromptFromAudio": "Qwen3-TTS Clone Prompt From Audio",
    "Qwen3SavePrompt": "Qwen3-TTS Save Prompt",
    "Qwen3LoadPrompt": "Qwen3-TTS Load Prompt",
    "Qwen3CustomVoiceFromPrompt": "Qwen3-TTS Custom Voice From Prompt",
    "Qwen3HybridCloneInstructPreset": "Qwen3-TTS Hybrid Clone+Instruct Preset",
    "Qwen3VoiceBoxInstruct": "Qwen3-TTS VoiceBox Instruct",
    "Qwen3VoiceBoxClone": "Qwen3-TTS VoiceBox Clone",
    "Qwen3VoiceBoxCloneInstruct": "Qwen3-TTS VoiceBox Clone+Instruct",
    "Qwen3VoiceBoxCloneExperiment": "Qwen3-TTS VoiceBox Clone Experiment",
    "Qwen3VoiceBoxMorphSpeaker": "Qwen3-TTS VoiceBox Morph Speaker",
    "Qwen3DatasetFromFolder": "Qwen3-TTS Dataset Maker",
    "Qwen3DataPrep": "Qwen3-TTS Data Prep",
    "Qwen3FineTune": "Qwen3-TTS Finetune",
    "Qwen3PlainCustomVoiceFineTune": "Qwen3-TTS Plain CustomVoice Finetune",
    "Qwen3VoiceBoxCreate": "Qwen3-TTS VoiceBox Create",
    "Qwen3UploadVoiceBoxToHub": "Qwen3-TTS Upload VoiceBox To Hub",
    "Qwen3VoiceBoxBootstrapFineTune": "Qwen3-TTS VoiceBox Bootstrap Finetune",
    "Qwen3VoiceBoxFineTune": "Qwen3-TTS VoiceBox Finetune",
    "Qwen3SFTBase12Hz": "Qwen3-TTS SFT Base 12Hz",
    "Qwen3SFTCustomVoice12Hz": "Qwen3-TTS SFT CustomVoice 12Hz",
    "Qwen3SFTVoiceBox12Hz": "Qwen3-TTS SFT VoiceBox 12Hz",
    "Qwen3SFTVoiceBoxBootstrap12Hz": "Qwen3-TTS SFT VoiceBox Bootstrap 12Hz",
    "Qwen3AudioCompare": "Qwen3-TTS Audio Compare"
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
